-- Database: FinancieraOh

-- DROP DATABASE IF EXISTS "FinancieraOh";

CREATE DATABASE "FinancieraOh"
    WITH
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'Spanish_Peru.1252'
    LC_CTYPE = 'Spanish_Peru.1252'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1
    IS_TEMPLATE = False;
	
 CREATE TABLE CLIENTE(
 ID_CLIENTE INTEGER NOT NULL PRIMARY KEY,
 NOMBRES VARCHAR NOT NULL,
 APELLIDOS VARCHAR NOT NULL,
 DNI VARCHAR NOT NULL,
 TELEFONO VARCHAR)
 
 CREATE TABLE VENTA (
    ID_VENTA INTEGER NOT NULL PRIMARY KEY,
    FECHA DATE NOT NULL,
    ID_CLIENTE INTEGER NOT NULL,
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE)
);
 
 CREATE TABLE DETALLE_VENTA (
    ID_DVENTA INTEGER NOT NULL,
    ID_PRODUCTO INTEGER NOT NULL,
    CANTIDAD INTEGER NOT NULL,
    ID_VENTA INTEGER NOT NULL,
    FOREIGN KEY (ID_VENTA) REFERENCES VENTA(ID_VENTA)
);
 
CREATE TABLE PRODUCTO (
    ID_PRODUCTO INTEGER NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR NOT NULL,
    PRECIO DECIMAL(10,2) NOT NULL
);